name: Build & Publish OpenSearch Docker Image with Plugins
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenSearch version (e.g. "latest" or "3.3.1")'
        required: true
        type: string
        default: 'latest'
env:
  IMAGE_NAME: wuzzy-opensearch
jobs:
  build-and-publish:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build image
        run: |
          echo "Building OpenSearch Docker image with version: ${{ inputs.version }}"
          cd opensearch
          docker build . \
            --tag $IMAGE_NAME \
            --label "runnumber=${GITHUB_RUN_ID}" \
            --build-arg VERSION=${{ inputs.version }}
      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $IMAGE_NAME $IMAGE_ID:${{ github.sha }}
          docker tag $IMAGE_NAME $IMAGE_ID:${{ inputs.version }}
          docker push $CONTAINER_REGISTRY_ADDR/$IMAGE_ID:${{ github.sha }}
          docker push $CONTAINER_REGISTRY_ADDR/$IMAGE_ID:${{ inputs.version }}
          docker push ghcr.io/$IMAGE_ID:${{ github.sha }}
          docker push ghcr.io/$IMAGE_ID:${{ inputs.version }}
