name: Build & Publish OpenSearch Docker Image with Plugins
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenSearch version (e.g. "latest" or "3.3.1")'
        required: true
        type: string
        default: 'latest'
env:
  IMAGE_NAME: wuzzy-opensearch
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build image
        run: |
          cd hyperbeam
          docker build . \
            --tag $IMAGE_NAME \
            --label "runnumber=${GITHUB_RUN_ID}" \
            --build-arg VERSION=${{ inputs.version }}
      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{ inputs.version }}
          echo IMAGE_ID=$IMAGE_ID
          echo SHA=${{ github.sha }}
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:${{ github.sha }}
          docker tag $IMAGE_NAME $IMAGE_ID:${VERSION}
          docker push $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:${VERSION}
